package com.nunchuk.android.bitbox

enum class BitBoxUserInteraction {
    NONE,
    UNLOCK_DEVICE,
    CONFIRM_PAIRING,
    VERIFY_ADDRESS,
    REGISTER_WALLET,
    SIGN_MESSAGE,
    SIGN_TRANSACTION,
    CONFIRM_DEVICE_NAME,
    SET_DEVICE_PASSWORD,
    SHOW_RECOVERY_WORDS,
    INSERT_SD_CARD,
    CREATE_BACKUP,
    RESTORE_FROM_RECOVERY_WORDS,
    RESTORE_FROM_BACKUP,
    CHANGE_DEVICE_PASSWORD,
    TOGGLE_MNEMONIC_PASSPHRASE,
    CHECK_BACKUP,
}
